# Use an official Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY src ./src
COPY setup.py .
COPY setup.cfg .


# Install dependencies
RUN pip install --upgrade pip


RUN pip install -e . 





