version: '3.8'

services:
  # Service to load parquet data
  load_parquet:
    build:
      context: .           # Build Docker image from current directory
      dockerfile: Dockerfile # Use the Dockerfile in this directory (corrected spelling)
    command: python src/parquet/load_parquet.py # Command to run for this service
    volumes:
      - ./data:/app/data   # Mount local data directory into the container
    working_dir: /app      # Set working directory inside the container

  # Service to compute statistics (e.g., median)
  load_csv:
    build:
      context: .           # Build Docker image from current directory
      dockerfile: Dockerfile # Use the Dockerfile in this directory (corrected spelling)
    command: python src/parquet/load_csv.py # Command to run for this service
    volumes:
      - ./data:/app/data   # Mount local data directory into the container
    working_dir: /app      # Set working directory inside the container